# Generated by Django 4.2.11 on 2026-02-04 11:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('color', models.CharField(default='#3498db', help_text='Hex color code for UI', max_length=7, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='corpus.category', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file', models.FileField(upload_to='corpus_documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt', 'pdf', 'doc', 'docx', 'rtf', 'odt', 'html', 'xml', 'json'])], verbose_name='Document File')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='File Size (bytes)')),
                ('file_hash', models.CharField(blank=True, help_text='For integrity verification', max_length=64, verbose_name='File Hash (SHA256)')),
                ('language', models.CharField(default='tr', help_text='ISO 639-1 code', max_length=10, verbose_name='Language')),
                ('word_count', models.IntegerField(default=0, verbose_name='Word Count')),
                ('char_count', models.IntegerField(default=0, verbose_name='Character Count')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_encrypted', models.BooleanField(default=False, verbose_name='Encrypted')),
                ('is_sensitive', models.BooleanField(default=False, help_text='Marks document as containing sensitive information', verbose_name='Sensitive Data')),
                ('content_text', models.TextField(blank=True, help_text='Extracted text for search indexing', verbose_name='Extracted Text')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Additional Metadata')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_documents', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='corpus.category', verbose_name='Category')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Compilation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Compilation Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_public', models.BooleanField(default=False, help_text='Make this compilation publicly accessible', verbose_name='Public')),
                ('total_documents', models.IntegerField(default=0, verbose_name='Total Documents')),
                ('total_words', models.BigIntegerField(default=0, verbose_name='Total Words')),
                ('total_characters', models.BigIntegerField(default=0, verbose_name='Total Characters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_compilations', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('documents', models.ManyToManyField(related_name='compilations', to='corpus.document', verbose_name='Documents')),
            ],
            options={
                'verbose_name': 'Compilation',
                'verbose_name_plural': 'Compilations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_controls', to='corpus.document')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_accesses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Access Control',
                'verbose_name_plural': 'Access Controls',
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-created_at'], name='corpus_docu_created_aadb70_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status', '-created_at'], name='corpus_docu_status_a9559a_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['category', '-created_at'], name='corpus_docu_categor_7b8627_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accesscontrol',
            unique_together={('document', 'user')},
        ),
    ]
